CREATE TABLE Image(
    Id UUID PRIMARY KEY,
    PathToSource VARCHAR(255) NOT NULL,
    CompressedPath VARCHAR(255) NOT NULL,
    ThumbnailPath VARCHAR(255)
);

ALTER TABLE Flowers
    ADD COLUMN PrimaryImageId UUID NOT NULL UNIQUE REFERENCES Image(Id);

CREATE TABLE FlowerImage(
    FlowerId UUID NOT NULL,
    ImageId UUID NOT NULL,
    PRIMARY KEY (FlowerId, ImageId),
    CONSTRAINT fk_flower FOREIGN KEY (FlowerId) REFERENCES Flowers(Id) ON DELETE RESTRICT,
    CONSTRAINT fk_image FOREIGN KEY (ImageId) REFERENCES Image(Id) ON DELETE RESTRICT
);