/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowersIndexRouteImport } from './routes/flowers/index'
import { Route as FlowersCreateIndexRouteImport } from './routes/flowers/create/index'
import { Route as FlowersFlowerIdIndexRouteImport } from './routes/flowers/$flowerId/index'

const HomeIndexLazyRouteImport = createFileRoute('/home/')()
const AuthSignUpIndexLazyRouteImport = createFileRoute('/auth/signUp/')()
const AuthSignInIndexLazyRouteImport = createFileRoute('/auth/signIn/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexLazyRoute = HomeIndexLazyRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/home/index.lazy').then((d) => d.Route))
const FlowersIndexRoute = FlowersIndexRouteImport.update({
  id: '/flowers/',
  path: '/flowers/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/flowers/index.lazy').then((d) => d.Route))
const AuthSignUpIndexLazyRoute = AuthSignUpIndexLazyRouteImport.update({
  id: '/auth/signUp/',
  path: '/auth/signUp/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/signUp/index.lazy').then((d) => d.Route),
)
const AuthSignInIndexLazyRoute = AuthSignInIndexLazyRouteImport.update({
  id: '/auth/signIn/',
  path: '/auth/signIn/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/signIn/index.lazy').then((d) => d.Route),
)
const FlowersCreateIndexRoute = FlowersCreateIndexRouteImport.update({
  id: '/flowers/create/',
  path: '/flowers/create/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/flowers/create/index.lazy').then((d) => d.Route),
)
const FlowersFlowerIdIndexRoute = FlowersFlowerIdIndexRouteImport.update({
  id: '/flowers/$flowerId/',
  path: '/flowers/$flowerId/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/flowers/$flowerId/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flowers': typeof FlowersIndexRoute
  '/home': typeof HomeIndexLazyRoute
  '/flowers/$flowerId': typeof FlowersFlowerIdIndexRoute
  '/flowers/create': typeof FlowersCreateIndexRoute
  '/auth/signIn': typeof AuthSignInIndexLazyRoute
  '/auth/signUp': typeof AuthSignUpIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flowers': typeof FlowersIndexRoute
  '/home': typeof HomeIndexLazyRoute
  '/flowers/$flowerId': typeof FlowersFlowerIdIndexRoute
  '/flowers/create': typeof FlowersCreateIndexRoute
  '/auth/signIn': typeof AuthSignInIndexLazyRoute
  '/auth/signUp': typeof AuthSignUpIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flowers/': typeof FlowersIndexRoute
  '/home/': typeof HomeIndexLazyRoute
  '/flowers/$flowerId/': typeof FlowersFlowerIdIndexRoute
  '/flowers/create/': typeof FlowersCreateIndexRoute
  '/auth/signIn/': typeof AuthSignInIndexLazyRoute
  '/auth/signUp/': typeof AuthSignUpIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flowers'
    | '/home'
    | '/flowers/$flowerId'
    | '/flowers/create'
    | '/auth/signIn'
    | '/auth/signUp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flowers'
    | '/home'
    | '/flowers/$flowerId'
    | '/flowers/create'
    | '/auth/signIn'
    | '/auth/signUp'
  id:
    | '__root__'
    | '/'
    | '/flowers/'
    | '/home/'
    | '/flowers/$flowerId/'
    | '/flowers/create/'
    | '/auth/signIn/'
    | '/auth/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowersIndexRoute: typeof FlowersIndexRoute
  HomeIndexLazyRoute: typeof HomeIndexLazyRoute
  FlowersFlowerIdIndexRoute: typeof FlowersFlowerIdIndexRoute
  FlowersCreateIndexRoute: typeof FlowersCreateIndexRoute
  AuthSignInIndexLazyRoute: typeof AuthSignInIndexLazyRoute
  AuthSignUpIndexLazyRoute: typeof AuthSignUpIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/': {
      id: '/flowers/'
      path: '/flowers'
      fullPath: '/flowers'
      preLoaderRoute: typeof FlowersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signUp/': {
      id: '/auth/signUp/'
      path: '/auth/signUp'
      fullPath: '/auth/signUp'
      preLoaderRoute: typeof AuthSignUpIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signIn/': {
      id: '/auth/signIn/'
      path: '/auth/signIn'
      fullPath: '/auth/signIn'
      preLoaderRoute: typeof AuthSignInIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/create/': {
      id: '/flowers/create/'
      path: '/flowers/create'
      fullPath: '/flowers/create'
      preLoaderRoute: typeof FlowersCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flowers/$flowerId/': {
      id: '/flowers/$flowerId/'
      path: '/flowers/$flowerId'
      fullPath: '/flowers/$flowerId'
      preLoaderRoute: typeof FlowersFlowerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowersIndexRoute: FlowersIndexRoute,
  HomeIndexLazyRoute: HomeIndexLazyRoute,
  FlowersFlowerIdIndexRoute: FlowersFlowerIdIndexRoute,
  FlowersCreateIndexRoute: FlowersCreateIndexRoute,
  AuthSignInIndexLazyRoute: AuthSignInIndexLazyRoute,
  AuthSignUpIndexLazyRoute: AuthSignUpIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
